server:
  port: 8762
  address: 0.0.0.0
  servlet:
    context-path: /


spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3308/hmily_order?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: order-service

mybatis:
  type-aliases-package: com.zoro.tcc.hmily.order.entity
  config-location: classpath:mybatis/mybatis-config.xml
#
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      registryFetchIntervalSeconds: 1 #从eureka服务器注册表中获取注册信息的时间间隔（s），默认为30秒
      leaseRenewalIntervalInSeconds: 1 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒
  instance:
    prefer-ip-address: true


#Ribbon的负载均衡策略
hmilyOrder :
  ribbon:
    NFLoadBalancerRuleClassName:  com.netflix.loadbalancer.RandomRule
    MaxAutoRetriesNextServer : 0
feign:
  hystrix:
    enabled : true
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能

logging:
  level:
    root: error
    org.springframework.web: info
    org.apache.ibatis: info
    org.dromara.hmily.bonuspoint: debug
    org.dromara.hmily.lottery: debug
    org.dromara.hmily: debug
    com.zoro: debug
    io.netty: info
    com:
      zoro: debug

#hmily参数配置
org:
  dromara:
    hmily :
      serializer : kryo
      recoverDelayTime : 30
      retryMax : 30
      scheduledDelay : 30
      scheduledThreadMax :  10
      repositorySupport : db
      started: true
      hmilyDbConfig :
        driverClassName  : com.mysql.cj.jdbc.Driver
        url :  jdbc:mysql://localhost:3308/hmily?useSSL=false&serverTimezone=UTC
        username : root
        password : root

#禁用ribbon重试 否则超时会自动重试
#[og-disruptor6-7] o.d.h.c.s.r.JdbcCoordinatorRepository : executeUpdate-> Duplicate entry '1086204287765487616' for key 'PRIMARY'
ribbon:
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false